### ISSUE TITLE
Oops! Koel installation or upgrade didn't finish successfully.

### ISSUE THREAD

**Issue by icofans** [Hyzual/docker-koel#29]
Attempting to install or upgrade Koel.
Remember, you can always install/upgrade manually following the guide here:
📙  https://docs.koel.dev

App key exists -- skipping
Generating JWT secret
Migrating database
Data seeded -- skipping
Now to front-end stuff
Oops! Koel installation or upgrade didn't finish successfully.
Please try again, or visit https://docs.koel.dev for manual installation.
😥 Sorry for this. You deserve better.

**Comment by Hyzual** [comment]
Hi, this error is unfortunate but a known issue. You can safely ignore it because the "front-end stuff" is already done while building the docker image.
Quoting from [the README](https://github.com/Hyzual/docker-koel/blob/master/README.md)
> /!\ koel:init will fail at the stage where it checks front-end assets. This is known and is due to the absence of node.js and yarn. koel's frontend assets are already built in this image so this step is not necessary.

I'm hoping that future releases of Koel are easier to install and will not produce such errors.
Have a good day !
