### ISSUE TITLE
admin account not working

### ISSUE THREAD

**Issue by dr01dy** [Hyzual/docker-koel#8]
running the newest push and not able to login with admin@koel.com / SoSecureMuchWow

Can pointers you can help me with ?

Much appreciated

**Comment by Hyzual** [comment]
Hi, yes you should first exec the `koel:init` command in the container.
`docker exec -it <container_name> php artisan koel:init`
The command will ask you for an admin email / password.
It is expected to fail at the "building frontend stuff" stage because yarn is not installed. Assets are already built so it's not a problem.
Did this help you ?

**Comment by dr01dy** [comment]
jeff@satellite:~$ docker exec -it koel bash
root@ec77866dfe23:/var/www/html# php artisan koel:init
Attempting to install or upgrade Koel.
Remember, you can always install/upgrade manually following the guide here:
📙  https://koel.phanan.net/docs

App key exists -- skipping
Generating JWT secret
SQLSTATE[HY000] [2002] No such file or directory

Koel cannot connect to the database. Let's set it up.

 Your DB driver of choice [MySQL/MariaDB]:
  [mysql     ] MySQL/MariaDB
  [pgsql     ] PostgreSQL
  [sqlsrv    ] SQL Server
  [sqlite-e2e] SQLite
 >

**Comment by Hyzual** [comment]
This container does not have its own database. It needs a separate database container.
For example, you can start a separate mysql container. In this container, you need to create
1. A user (for example "koel")
2. A password for that user
3. A database (for example "koel")

See the [docker-compose.yml](https://github.com/Hyzual/docker-koel/blob/master/docker-compose.yml) file included as an example. Here, I use `mysql/mysql-server:5.7` and I pass it environment variables so the container creates a user and a database by itself when it starts.
The easiest way to run koel is to use docker-compose so that koel and the database are on the same network and can communicate.
