### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by Damix48** [Hyzual/docker-koel#9]
Hi, how can I configure the DB?

![image](https://user-images.githubusercontent.com/23702345/77260227-0c3e0f80-6c87-11ea-847e-0f3a439f65a0.png)

**Comment by dr01dy** [comment]
I am seeing the same problem

root@ed9104e7f2e7:/var/www/html# php artisan koel:init
Attempting to install or upgrade Koel.
Remember, you can always install/upgrade manually following the guide here:
📙  https://koel.phanan.net/docs

App key exists -- skipping
Generating JWT secret
SQLSTATE[HY000] [2002] No such file or directory

Koel cannot connect to the database. Let's set it up.

 Your DB driver of choice [MySQL/MariaDB]:
  [mysql     ] MySQL/MariaDB
  [pgsql     ] PostgreSQL
  [sqlsrv    ] SQL Server
  [sqlite-e2e] SQLite

**Comment by Hyzual** [comment]
Hi @Damix48 
This container does not have its own database. It needs a separate database container.
For example, you can start a separate mysql container. In this container, you need to create
1. A user (for example "koel")
2. A password for that user
3. A database (for example "koel")

See the [docker-compose.yml](https://github.com/Hyzual/docker-koel/blob/master/docker-compose.yml) file included as an example. Here, I use `mysql/mysql-server:5.7` and I pass it environment variables so the container creates a user and a database by itself when it starts.
The easiest way to run koel is to use docker-compose so that koel and the database are on the same network and can communicate.

**Comment by Damix48** [comment]
Thank you so much.

**Comment by Hyzual** [comment]
I've updated the [README](https://github.com/Hyzual/docker-koel/blob/master/README.md) to better explain how to run this container alongside another MySQL container.
